language: java
jdk:
- openjdk11

sudo: required
services:
  - docker

install:
  - mvn install

script:
  - docker build -t inseefr/queen-back-office .

deploy:
  - skip_cleanup: true
    provider: script
    script:
      echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      && docker push inseefr/queen-back-office
    on:
      branch: master

