language: java
jdk:
- openjdk11

services:
  - docker

script:
  - mvn install -B -V
  - docker build -t inseefr/queen-bo .

deploy:
  skip_cleanup: true
  provider: script
  script:
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    && docker push inseefrlab/queen-bo
  on:
    branch: master

k8s_restart:
  skip_cleanup: true
  provider: script
  script:
    curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl
    && chmod +x kubectl
    && ./kubectl --token $K8S_TOKEN --server $K8S_SERVER --insecure-skip-tls-verify rollout restart deployment/queen-bo -n queen
  on:
    branch: master

env:
  global:
    - secure:
    - secure:
    - secure:

