apiVersion: apps/v1
kind: Deployment
metadata:
  name: queen-bo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queen-bo
  template:
    metadata:
      labels:
        app: queen-bo
    spec:
      containers:
        - name: queen-bo
          image: inseefr/queen-back-office:latest
          env:
           - name: JAVA_OPTS
             value: '-Dspring.profiles.active=prod -Dspring.config.location=classpath:/,${CATALINA_BASE}/webapps/queenbo.properties -Dspring.config.additional-location=classpath:/,${CATALINA_BASE}/webapps/colmcolb.properties -Dlogging.config=classpath:log4j2.xml'
